DEPLOY_REMOTE_USER="ubuntu"
DEPLOY_REMOTE_HOST="52.67.135.170"
DEPLOY_SSH_KEY="/home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/core/inatto01-sp.pem"
DEPLOY_REMOTE_DIR="/home/ubuntu/apps/infra/monitor-app"
