# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /etc/letsencrypt/archive/orbital.anpprev.org
cert = /etc/letsencrypt/live/orbital.anpprev.org/cert.pem
privkey = /etc/letsencrypt/live/orbital.anpprev.org/privkey.pem
chain = /etc/letsencrypt/live/orbital.anpprev.org/chain.pem
fullchain = /etc/letsencrypt/live/orbital.anpprev.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = f840ea449f41e5acd813b09c40a0fee1
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
