# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/sinproprev.org.br
cert = /etc/letsencrypt/live/sinproprev.org.br/cert.pem
privkey = /etc/letsencrypt/live/sinproprev.org.br/privkey.pem
chain = /etc/letsencrypt/live/sinproprev.org.br/chain.pem
fullchain = /etc/letsencrypt/live/sinproprev.org.br/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 06ed6011ea54e4b229fdd1ac65ac6e0e
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
