#!/usr/bin/env bash
# cd /home/daniel/Code/infra/amazon-infra/lightsail/44.219.174.82/domains

REMOTE_USER="ubuntu"
REMOTE_HOST="44.219.174.82"
SSH_KEY="/home/daniel/amazon.ssh"

SITE_NAME="email.anpprev.org"
APP_NAME="email-app"
REMOTE_APP_DIR="/home/ubuntu/apps/email-app"

DOMAINS=(
  "email.anpprev.org"
)

# Portas padronizadas da aplicação base email-app.
WEB_UPSTREAM_HOST="127.0.0.1"
WEB_UPSTREAM_PORT="4005"
API_UPSTREAM_HOST="127.0.0.1"
API_UPSTREAM_PORT="8005"

SSL_EMAIL="danielmaiax@gmail.com"
CLIENT_MAX_BODY_SIZE="20m"
WEB_PROXY_READ_TIMEOUT="60s"
API_PROXY_READ_TIMEOUT="120s"
API_PROXY_CONNECT_TIMEOUT="30s"
API_PROXY_SEND_TIMEOUT="120s"

