#!/usr/bin/env bash
# cd /home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/domains

REMOTE_USER="ubuntu"
REMOTE_HOST="52.67.135.170"
SSH_KEY="/home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/core/inatto01-sp.pem"

SITE_NAME="monitor.inatto.com"
APP_NAME="amazon-infra-monitor"
REMOTE_APP_DIR="/home/ubuntu/apps/infra/monitor-app"

DOMAINS=(
  "monitor.inatto.com"
)

WEB_UPSTREAM_HOST="127.0.0.1"
WEB_UPSTREAM_PORT="4005"
API_UPSTREAM_HOST="127.0.0.1"
API_UPSTREAM_PORT="8005"

SSL_EMAIL="danielmaiax@gmail.com"
CLIENT_MAX_BODY_SIZE="1m"
WEB_PROXY_READ_TIMEOUT="30s"
API_PROXY_READ_TIMEOUT="30s"
API_PROXY_CONNECT_TIMEOUT="5s"
API_PROXY_SEND_TIMEOUT="30s"

