#!/usr/bin/env bash
# cd /home/daniel/Code/infra/amazon-infra/lightsail/44.194.90.24/domains

REMOTE_USER="ubuntu"
REMOTE_HOST="44.194.90.24"
SSH_KEY="/home/daniel/amazon.ssh"

SITE_NAME="station.anpprev.org"
APP_NAME="station-app"
REMOTE_APP_DIR="/home/ubuntu/apps/station-app"

DOMAINS=(
  "station.anpprev.org"
)

# Portas padronizadas da aplicação base station-app.
WEB_UPSTREAM_HOST="127.0.0.1"
WEB_UPSTREAM_PORT="4002"
API_UPSTREAM_HOST="127.0.0.1"
API_UPSTREAM_PORT="8002"

SSL_EMAIL="danielmaiax@gmail.com"
CLIENT_MAX_BODY_SIZE="20m"
WEB_PROXY_READ_TIMEOUT="60s"
API_PROXY_READ_TIMEOUT="120s"
API_PROXY_CONNECT_TIMEOUT="30s"
API_PROXY_SEND_TIMEOUT="120s"

SYSTEMD_SERVICES=(
  "station-api.service"
  "station-web.service"
)
